import hashlib
import pandas as pd
import matplotlib.pyplot as plt
import tkinter as tk
from tkinter import filedialog, messagebox
from fpdf import FPDF
from datetime import datetime
import os
import shutil  # For Zipping and Deleting folders

# =============================================================================
# CLASS: ForensicReport
# PURPOSE: Handles the generation of the PDF forensic report.
# =============================================================================
class ForensicReport(FPDF):
    def header(self):
        """Creates the header for every page of the PDF report."""
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'DIGITAL FORENSIC LAB REPORT', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Generated by IRISNeT Analyzer | Court Admissible Format', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        """Creates the footer with page numbers."""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        """Standard styling for section titles."""
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255) # Light blue background
        self.cell(0, 10, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        """Standard styling for body text."""
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 8, body)
        self.ln()

# =============================================================================
# FORENSIC LOGIC FUNCTIONS
# =============================================================================
def hash_file(filename):
    """Calculates SHA-256 hash. Used to verify evidence integrity."""
    sha256 = hashlib.sha256()
    try:
        with open(filename, "rb") as f:
            for block in iter(lambda: f.read(4096), b""):
                sha256.update(block)
        return sha256.hexdigest()
    except FileNotFoundError:
        return "ERROR_FILE_NOT_FOUND"

def parse_log(filename):
    """Parses Authentication Logs (Auth Logs)."""
    data = []
    try:
        with open(filename, "r") as file:
            for line in file:
                # Expected format: Date Time Message
                parts = line.strip().split(" ", 2)
                if len(parts) < 3: continue
                date, time, message = parts
                data.append([date, time, message])
        
        df = pd.DataFrame(data, columns=["Date", "Time", "Message"])
        df["Datetime"] = pd.to_datetime(df["Date"] + " " + df["Time"])
        # Extract IP address for identification
        df["IP"] = df["Message"].str.extract(r'(\d+\.\d+\.\d+\.\d+)')
        return df
    except Exception as e:
        return None

def detect_suspicious(df):
    """Analyzes Auth Logs for failed access keywords."""
    failed_logins = df[df["Message"].str.contains("Failed|Invalid", case=False, na=False)]
    ip_count = failed_logins["IP"].value_counts()
    return failed_logins, ip_count

# =============================================================================
# CLASS: ForensicApp (The User Interface)
# =============================================================================
class ForensicApp:
    def __init__(self, root):
        self.root = root
        self.root.title("IRISNeT Forensic Suite v3.1 (Professional)")
        self.root.geometry("600x600")
        
        self.filepath = tk.StringVar()
        self.case_id = tk.StringVar()
        self.investigator = tk.StringVar()
        
        self.create_widgets()

    def create_widgets(self):
        tk.Label(self.root, text="DIGITAL FORENSIC TOOL", font=("Arial", 18, "bold"), fg="darkblue").pack(pady=15)
        tk.Label(self.root, text="Authentication Log Analysis & Integrity Check", font=("Arial", 10, "italic")).pack()

        frame = tk.LabelFrame(self.root, text="Investigation Details", padx=10, pady=10)
        frame.pack(padx=20, pady=10, fill="x")

        tk.Label(frame, text="Case ID:").grid(row=0, column=0, sticky="e")
        tk.Entry(frame, textvariable=self.case_id, width=35).grid(row=0, column=1, padx=5, pady=5)

        tk.Label(frame, text="Investigator:").grid(row=1, column=0, sticky="e")
        tk.Entry(frame, textvariable=self.investigator, width=35).grid(row=1, column=1, padx=5, pady=5)

        tk.Label(frame, text="Auth Log File:").grid(row=2, column=0, sticky="e")
        tk.Entry(frame, textvariable=self.filepath, width=35).grid(row=2, column=1, padx=5, pady=5)
        tk.Button(frame, text="Browse", command=self.browse_file).grid(row=2, column=2, padx=5)

        tk.Button(self.root, text="RUN ANALYSIS & CREATE EVIDENCE ZIP", bg="darkred", fg="white", font=("Arial", 11, "bold"), command=self.run_analysis).pack(pady=20)

        self.log_box = tk.Text(self.root, height=12, width=65, bg="#f0f0f0")
        self.log_box.pack(pady=5)

    def log(self, msg):
        self.log_box.insert(tk.END, f">> {msg}\n")
        self.log_box.see(tk.END)

    def browse_file(self):
        filename = filedialog.askopenfilename(title="Select Authentication Log")
        self.filepath.set(filename)

    def run_analysis(self):
        log_path = self.filepath.get()
        case = self.case_id.get()
        officer = self.investigator.get()

        if not log_path or not case:
            messagebox.showerror("Error", "Please fill in Case ID and select a file.")
            return

        # 1. SETUP FOLDERS
        safe_case_id = "".join([c for c in case if c.isalnum() or c in (' ', '-', '_')]).strip()
        output_folder = f"{safe_case_id}_Evidence_Package"
        
        # Ensure we start with a clean folder
        if os.path.exists(output_folder):
            shutil.rmtree(output_folder)
        os.makedirs(output_folder)
        
        report_path = os.path.join(output_folder, f"Forensic_Report_{safe_case_id}.pdf")
        graph_path = os.path.join(output_folder, "timeline_graph.png")
        log_copy_path = os.path.join(output_folder, os.path.basename(log_path))

        self.log("Initializing forensic engine...")
        
        # 2. HASHING (Integrity Baseline)
        file_hash = hash_file(log_path)
        self.log(f"FILE INTEGRITY HASH: {file_hash[:15]}...")

        # 3. PARSING
        df = parse_log(log_path)
        if df is None:
            self.log("Error: File Corrupted or Unreadable.")
            return
        
        # 4. ANALYSIS
        failed, ip_counts = detect_suspicious(df)
        self.log(f"Suspicious events found: {len(failed)}")

        # 5. VISUALIZATION
        if not failed.empty:
            plt.figure(figsize=(10,4))
            plt.plot(failed["Datetime"], range(1, len(failed)+1), marker='o', color='red', label='Failed Login')
            plt.title("Timeline of Failed Authentication Events")
            plt.xlabel("Timestamp")
            plt.ylabel("Cumulative Failed Attempts")
            plt.legend()
            plt.grid(True)
            plt.tight_layout()
            plt.savefig(graph_path)
            plt.close()

        # 6. REPORT GENERATION
        pdf = ForensicReport()
        pdf.add_page()
        
        # Ch 1: Info
        pdf.chapter_title("1. Case Information")
        pdf.chapter_body(f"Case ID: {case}\nInvestigator: {officer}\nDate: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        
        # Ch 2: Integrity
        pdf.chapter_title("2. Evidence Integrity Check")
        pdf.chapter_body(f"File Name: {os.path.basename(log_path)}\n"
                         f"SHA-256 Hash: {file_hash}\n"
                         f"Integrity Status: VERIFIED\n\n"
                         "Note: This hash confirms the file state at the time of analysis.")

        # Ch 3: Findings Table
        pdf.chapter_title("3. Analysis Findings")
        pdf.set_font('Arial', '', 12)
        pdf.cell(0, 10, f"Total Failed Attempts Detected: {len(failed)}", ln=True)
        pdf.ln(5)

        if not ip_counts.empty:
            # Table Header
            pdf.set_font('Arial', 'B', 12)
            pdf.set_fill_color(230, 230, 230)
            pdf.cell(95, 10, "Source IP Address", 1, 0, 'C', 1)
            pdf.cell(95, 10, "Failed Attempts", 1, 1, 'C', 1)
            
            # Table Body
            pdf.set_font('Arial', '', 12)
            for ip, count in ip_counts.items():
                pdf.cell(95, 10, str(ip), 1, 0, 'C')
                pdf.cell(95, 10, str(count), 1, 1, 'C')
        else:
            pdf.chapter_body("No suspicious authentication events detected.")
        
        pdf.ln(10)

        # Ch 4: Visuals (Forces new page)
        if os.path.exists(graph_path):
            pdf.add_page()
            pdf.chapter_title("4. Attack Visualization")
            pdf.image(graph_path, x=10, w=180)
            pdf.chapter_body("Figure 1: Timeline showing the frequency of failed login attempts.")

        pdf.output(report_path)
        self.log("PDF Report Generated.")

        # 7. PACKAGING (Clean Up)
        try:
            shutil.copy(log_path, log_copy_path) # Preserve evidence
            
            # Create the ZIP file
            shutil.make_archive(output_folder, 'zip', output_folder)
            self.log(f"SUCCESS: Package zipped as {output_folder}.zip")
            
            # --- NEW: DELETE THE FOLDER ---
            shutil.rmtree(output_folder)
            self.log("Cleaned up temporary files.")
            # ------------------------------
            
            messagebox.showinfo("Success", f"Evidence Package Created!\n\nLocation: {output_folder}.zip")
        except Exception as e:
            self.log(f"Error Zipping: {e}")

if __name__ == "__main__":
    root = tk.Tk()
    app = ForensicApp(root)
    root.mainloop()